
services:
  frontend:
    image: <your-dockerhub-username>/<frontend-dockerimage-name>
    container_name: node-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:5001/api
    networks:
      - frontend-backend
    stdin_open: true
    tty: true

  backend:
    image: <your-dockerhub-username>/<backend-dockerimage-name>
    container_name: node-backend
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - MONGO_URI=mongodb://admin:admin123@database:27017/tier-demo?authSource=admin
    depends_on:
      - database
    networks:
      - frontend-backend
      - backend-database

  database:
    image: <your-dockerhub-username>/<database-dockerimage-name>
    container_name: mongo-db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongo-data:/data/db
    networks:
      - backend-database

networks:
  frontend-backend:
  backend-database:

volumes:
  mongo-data:
